export const currency_codes ={
                                "?": "?",
                                // "USD": "$",
                                // "EUR": "€",
                                // "GBP": "£",
                                // "KRW": "₩",
                                // "RUB": "₽",
                                // "BRL": "R$",
                                // "JPY": "¥",
                                // "CLP": "$",
                                // "AUD": "$",
                                // "CNY": "¥",
                                // "CAD": "$",
                                // "HKD": "HK$",
                                // "CHF": "CHF",
                                // "PLN": "zł",
                                // "TRY": "TRY",
                                // "SGD": "S$",
                                // "MYR": "RM",
                                // "VND": "VND",
                                // "THB": "฿",
                                // "IDR": "Rp",
                                // "BYR": "Br",
                                // "UAH": "₴",
                                // "SEK": "kr",
                                // "DKK": "kr.",
                                // "NOK": "kr",
                                // "ZAR": "R",
                                // "NZD": "NZD",
                                // "ILS": "₪",
                                // "MXN": "Mex$",
                                // "PEN": "S/.",
                                // "COP": "COP",
                                // "BDT": "৳",
                                // "LKR": "Rs",
                                // "NIO": "Có$",
                                // "TWD": "NT$",
                                // "PHP": "₱",
                                // "INR": "र",
                                // "NGN": "₦",
                                // "TJS": "TJS",
                                // "KGS": "KGS",
                                // "LEU":"lei",
                                // "ARS":"$",
                                // "BTC":"Ƀ",
                                // "CNH":"¥",
                                // "HUF":"Ft",
                                // "RMB":"CN¥",
                                // "TND":"DT",
                                // "AED":"د.إ",
                                
                                "AED"      : "د.إ",
                                "ANG"      : "ƒ",
                                "AOA"      : "AOA",
                                "ARS"      : "$",
                                "AUD"      : "A$",
                                "BAM"      : "KM",
                                "BBD"      : "$",
                                "BGN"      : "лв",
                                "BHD"      : "BD",
                                "BND"      : "$",
                                "BRL"      : "R$",
                                "CAD"      : "C$",
                                "CHF"      : "Fr",
                                "CLF"      : "UF",
                                "CLP"      : "$",
                                "CNY"      : "¥",
                                "COP"      : "$",
                                "CRC"      : "₡",
                                "CZK"      : "Kč",
                                "DKK"      : "kr",
                                "EEK"      : "KR",
                                "EGP"      : "E£",
                                "EUR"      : "€",
                                "FJD"      : "FJ$",
                                "GBP"      : "£",
                                "GTQ"      : "Q",
                                "HKD"      : "$",
                                "HRK"      : "kn",
                                "HUF"      : "Ft",
                                "IDR"      : "Rp",
                                "ILS"      : "₪",
                                "INR"      : "Rs",
                                "JOD"      : "د.ا",
                                "JPY"      : "¥",
                                "KES"      : "KSh",
                                "KRW"      : "₩",
                                "KWD"      : "KD",
                                "KYD"      : "$",
                                "LTL"      : "Lt",
                                "LVL"      : "Ls",
                                "MAD"      : "د.م",
                                "MVR"      : "Rf",
                                "MXN"      : "$",
                                "MYR"      : "RM",
                                "NGN"      : "₦",
                                "NOK"      : "kr",
                                "NZD"      : "$",
                                "OMR"      : "OMR",
                                "PEN"      : "S/.",
                                "PHP"      : "₱",
                                "PLN"      : "zł",
                                "QAR"      : "QAR",
                                "RON"      : "lei",
                                "RUB"      : "руб",
                                "SAR"      : "SAR",
                                "SEK"      : "kr",
                                "SGD"      : "$",
                                "THB"      : "฿",
                                "TRY"      : "TL",
                                "TTD"      : "$",
                                "TWD"      : "$",
                                "UAH"      : "₴",
                                "USD"      : "$",
                                "VEF"      : "Bs",
                                "VND"      : "₫",
                                "XCD"      : "$",
                                "ZAR"      : "R"
                            }
