import { mobiscroll } from '../src/js/modules/mobiscroll.angular';
export * from '../src/js/modules/mobiscroll.angular';
import '../src/js/themes/ios';
import '../src/js/themes/bootstrap';
import '../src/js/themes/mobiscroll-dark';
import '../src/js/themes/material';
import '../src/js/themes/material-dark';
import '../src/js/themes/ios-dark';
import '../src/js/themes/windows';
import '../src/js/themes/windows-dark';
import '../src/js/themes/auto-theme';
export default mobiscroll;
